apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 30 # время на graceful shutdown
      containers:
        - name: my-app
          image: shestera/scaletestapp
          resources:
            requests:
              memory: "15Mi"
            limits:
              memory: "30Mi"
          readinessProbe:
            httpGet:
              path: /healthz # поменяй, если в приложении другой путь для проверки готовности
              port: 8080 # замени на порт приложения, если не 8080
            initialDelaySeconds: 1
            periodSeconds: 2
            failureThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"] # пауза для снятия пода с нагрузки
