apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: shestera/scaletestapp
          resources:
            requests:
              memory: "15Mi"
            limits:
              memory: "30Mi"
